// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// b_ism_rcpp
Rcpp::List b_ism_rcpp(arma::mat data, int i_index, int t_index, int y_index, long long Ndraw, long long Nburn, std::string b_prior, double lambda_b, double c0, double C0, double va, double vb, double tau, bool geweke, bool use_phiinit, bool const_val, bool ife, bool tfe, bool iis, bool sis);
RcppExport SEXP _bisam_b_ism_rcpp(SEXP dataSEXP, SEXP i_indexSEXP, SEXP t_indexSEXP, SEXP y_indexSEXP, SEXP NdrawSEXP, SEXP NburnSEXP, SEXP b_priorSEXP, SEXP lambda_bSEXP, SEXP c0SEXP, SEXP C0SEXP, SEXP vaSEXP, SEXP vbSEXP, SEXP tauSEXP, SEXP gewekeSEXP, SEXP use_phiinitSEXP, SEXP const_valSEXP, SEXP ifeSEXP, SEXP tfeSEXP, SEXP iisSEXP, SEXP sisSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type i_index(i_indexSEXP);
    Rcpp::traits::input_parameter< int >::type t_index(t_indexSEXP);
    Rcpp::traits::input_parameter< int >::type y_index(y_indexSEXP);
    Rcpp::traits::input_parameter< long long >::type Ndraw(NdrawSEXP);
    Rcpp::traits::input_parameter< long long >::type Nburn(NburnSEXP);
    Rcpp::traits::input_parameter< std::string >::type b_prior(b_priorSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_b(lambda_bSEXP);
    Rcpp::traits::input_parameter< double >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< double >::type C0(C0SEXP);
    Rcpp::traits::input_parameter< double >::type va(vaSEXP);
    Rcpp::traits::input_parameter< double >::type vb(vbSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< bool >::type geweke(gewekeSEXP);
    Rcpp::traits::input_parameter< bool >::type use_phiinit(use_phiinitSEXP);
    Rcpp::traits::input_parameter< bool >::type const_val(const_valSEXP);
    Rcpp::traits::input_parameter< bool >::type ife(ifeSEXP);
    Rcpp::traits::input_parameter< bool >::type tfe(tfeSEXP);
    Rcpp::traits::input_parameter< bool >::type iis(iisSEXP);
    Rcpp::traits::input_parameter< bool >::type sis(sisSEXP);
    rcpp_result_gen = Rcpp::wrap(b_ism_rcpp(data, i_index, t_index, y_index, Ndraw, Nburn, b_prior, lambda_b, c0, C0, va, vb, tau, geweke, use_phiinit, const_val, ife, tfe, iis, sis));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bisam_b_ism_rcpp", (DL_FUNC) &_bisam_b_ism_rcpp, 20},
    {NULL, NULL, 0}
};

RcppExport void R_init_bisam(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
