name: R Package Auto-Build

on:
  push:
    branches:
      - package_v2

jobs:
  build-r-package:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches
    
    - name: Setup Git Identity
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
    
    - name: Create or Reset r-package-build Branch
      run: |
        # Check if r-package-build branch exists
        if git ls-remote --heads origin r-package-build | grep r-package-build; then
          echo "Branch exists, resetting"
          git checkout package_v2
          git branch -D r-package-build || true
          git checkout -b r-package-build
        else
          echo "Branch doesn't exist, creating"
          git checkout -b r-package-build
        fi
    
    - name: Restructure Files for R Package
      run: |
        # Create a temporary directory
        mkdir -p temp_build
        
        # Move all files from bisam_v2 to temp directory
        echo "Moving bisam_v2 files to temporary directory"
        cp -r bisam_v2/* temp_build/
        
        # Remove everything except .git, .github and temp_build
        find . -mindepth 1 -maxdepth 1 -not -path "./.git" -not -path "./.github" -not -path "./temp_build" -exec rm -rf {} \;
        
        # Move everything from temp_build to root
        echo "Moving files from temporary directory to root"
        cp -r temp_build/* .
        rm -rf temp_build
        
        # Ensure src directory exists
        mkdir -p src
        
        # Copy mombf source files to src/
        echo "Copying mombf files to src/"
        cp -v mombf/mombf/src/*.cpp src/ || echo "No mombf cpp files found"
        cp -v mombf/mombf/src/*.h src/ || echo "No mombf header files found"
        
        # Copy lasso library files to src/
        echo "Copying lasso files to src/"
        cp -v lib/lasso/*.cpp src/ || echo "No lasso cpp files found"
        cp -v lib/lasso/*.h src/ || echo "No lasso header files found"
        
        # List all files in src/ to verify
        echo "Files in src/ directory:"
        ls -la src/
        
        # List all files in root to verify
        echo "Files in root directory:"
        ls -la
    
    - name: Check for Modified Files
      id: check_modified
      run: |
        git status --porcelain
        if [[ -n $(git status --porcelain) ]]; then
          echo "modified=true" >> $GITHUB_OUTPUT
        else
          echo "modified=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and Push Changes
      if: steps.check_modified.outputs.modified == 'true'
      run: |
        git add .
        git commit -m "Auto-update R package structure [skip ci]"
        git push -f origin r-package-build
        echo "Successfully pushed to r-package-build branch"